# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'thesis.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1143, 685)
        MainWindow.setMinimumSize(QtCore.QSize(259, 0))
        MainWindow.setStyleSheet("color: rgb(255, 210, 119);\n"
"gridline-color: rgb(33, 57, 86);\n"
"background-color: rgb(46, 80, 120);\n"
"selection-color: rgb(237, 85, 59);\n"
"\n"
"selection-background-color: rgb(33, 57, 86);")
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowNestedDocks|QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks|QtWidgets.QMainWindow.ForceTabbedDocks|QtWidgets.QMainWindow.VerticalTabs)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.comboBox_1 = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comboBox_1.sizePolicy().hasHeightForWidth())
        self.comboBox_1.setSizePolicy(sizePolicy)
        self.comboBox_1.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(35, 35, 35);\n"
"color: rgb(255, 210, 119);\n"
"selection-color: rgb(237, 85, 59);\n"
"\n"
"selection-background-color: rgb(33, 57, 86);\n"
"gridline-color: rgb(255, 255, 255);\n"
"")
        self.comboBox_1.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_1.setFrame(False)
        self.comboBox_1.setObjectName("comboBox_1")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.gridLayout_9.addWidget(self.comboBox_1, 0, 0, 1, 1)
        self.radioButton_1 = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.radioButton_1.sizePolicy().hasHeightForWidth())
        self.radioButton_1.setSizePolicy(sizePolicy)
        self.radioButton_1.setStyleSheet("color: rgb(255, 255, 255);")
        self.radioButton_1.setChecked(False)
        self.radioButton_1.setObjectName("radioButton_1")
        self.gridLayout_9.addWidget(self.radioButton_1, 0, 1, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setStyleSheet("\n"
"color: rgb(255, 255, 255);")
        self.radioButton_2.setChecked(False)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout_9.addWidget(self.radioButton_2, 0, 2, 1, 1)
        self.widget_1 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget_1.sizePolicy().hasHeightForWidth())
        self.widget_1.setSizePolicy(sizePolicy)
        self.widget_1.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_1.setStyleSheet("background-color: rgb(33, 57, 86);\n"
"border-color: rgb(0,0,0);\n"
"gridline-color: rgb(0, 0, 0);")
        self.widget_1.setObjectName("widget_1")
        self.gridLayout_9.addWidget(self.widget_1, 1, 0, 1, 3)
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comboBox_2.sizePolicy().hasHeightForWidth())
        self.comboBox_2.setSizePolicy(sizePolicy)
        self.comboBox_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(35, 35, 35);\n"
"color: rgb(255, 210, 119);\n"
"selection-color: rgb(237, 85, 59);\n"
"selection-background-color: rgb(33, 57, 86);\n"
"border-color: rgb(85, 170, 255);\n"
"border-top-color: rgb(85, 255, 255);\n"
"border-right-color: rgb(85, 255, 255);\n"
"border-bottom-color: rgb(85, 255, 255);\n"
"border-left-color: rgb(85, 255, 255);\n"
"gridline-color: rgb(255, 255, 255);\n"
"")
        self.comboBox_2.setFrame(False)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_9.addWidget(self.comboBox_2, 2, 0, 1, 1)
        self.radioButton_3 = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.radioButton_3.sizePolicy().hasHeightForWidth())
        self.radioButton_3.setSizePolicy(sizePolicy)
        self.radioButton_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.radioButton_3.setChecked(True)
        self.radioButton_3.setObjectName("radioButton_3")
        self.gridLayout_9.addWidget(self.radioButton_3, 2, 1, 1, 1)
        self.radioButton_4 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.radioButton_4.setObjectName("radioButton_4")
        self.gridLayout_9.addWidget(self.radioButton_4, 2, 2, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_2.setSizeIncrement(QtCore.QSize(5, 5))
        self.widget_2.setStyleSheet("background-color: rgb(33, 57, 86);\n"
"border-color: rgb(0,0,0);\n"
"gridline-color: rgb(0, 0, 0);")
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_9.addWidget(self.widget_2, 3, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1143, 26))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget_1 = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_1.setMinimumSize(QtCore.QSize(366, 534))
        self.dockWidget_1.setMouseTracking(True)
        self.dockWidget_1.setFloating(False)
        self.dockWidget_1.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidget_1.setObjectName("dockWidget_1")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(331, 251))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_20 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_20.setStyleSheet("background-color: rgb(32, 99, 155);\n"
"font: 9pt \"MS Shell Dlg 2\";")
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 0, 3, 1, 1)
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_4.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_4.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_4.setSizePolicy(sizePolicy)
        self.doubleSpinBox_4.setStyleSheet("background-color: rgb(35, 35, 35);\n"
"selection-color: rgb(237, 85, 59);\n"
"selection-background-color: rgb(33, 57, 86);\n"
"\n"
"font: 11pt \"Calibri\";")
        self.doubleSpinBox_4.setProperty("showGroupSeparator", False)
        self.doubleSpinBox_4.setDecimals(0)
        self.doubleSpinBox_4.setMaximum(5.0)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.gridLayout_2.addWidget(self.doubleSpinBox_4, 2, 3, 1, 1)
        self.doubleSpinBox_6 = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_6.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_6.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_6.setSizePolicy(sizePolicy)
        self.doubleSpinBox_6.setStyleSheet("background-color: rgb(35, 35, 35);\n"
"selection-color: rgb(237, 85, 59);\n"
"selection-background-color: rgb(33, 57, 86);\n"
"\n"
"font: 11pt \"Calibri\";")
        self.doubleSpinBox_6.setProperty("showGroupSeparator", False)
        self.doubleSpinBox_6.setDecimals(0)
        self.doubleSpinBox_6.setMaximum(5.0)
        self.doubleSpinBox_6.setObjectName("doubleSpinBox_6")
        self.gridLayout_2.addWidget(self.doubleSpinBox_6, 3, 3, 1, 1)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_2.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_2.setSizePolicy(sizePolicy)
        self.doubleSpinBox_2.setStyleSheet("background-color: rgb(35, 35, 35);\n"
"selection-color: rgb(237, 85, 59);\n"
"selection-background-color: rgb(33, 57, 86);\n"
"\n"
"font: 11pt \"Calibri\";")
        self.doubleSpinBox_2.setProperty("showGroupSeparator", False)
        self.doubleSpinBox_2.setDecimals(0)
        self.doubleSpinBox_2.setMaximum(5.0)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.gridLayout_2.addWidget(self.doubleSpinBox_2, 1, 3, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_2.sizePolicy().hasHeightForWidth())
        self.checkBox_2.setSizePolicy(sizePolicy)
        self.checkBox_2.setText("")
        self.checkBox_2.setChecked(False)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_2.addWidget(self.checkBox_2, 1, 2, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_4.sizePolicy().hasHeightForWidth())
        self.checkBox_4.setSizePolicy(sizePolicy)
        self.checkBox_4.setText("")
        self.checkBox_4.setChecked(False)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout_2.addWidget(self.checkBox_4, 2, 2, 1, 1)
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_6.sizePolicy().hasHeightForWidth())
        self.checkBox_6.setSizePolicy(sizePolicy)
        self.checkBox_6.setText("")
        self.checkBox_6.setChecked(False)
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout_2.addWidget(self.checkBox_6, 3, 2, 1, 1)
        self.labe = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labe.sizePolicy().hasHeightForWidth())
        self.labe.setSizePolicy(sizePolicy)
        self.labe.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";\n"
"color: rgb(255,255,255);")
        self.labe.setObjectName("labe")
        self.gridLayout_2.addWidget(self.labe, 1, 0, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";\n"
"color: rgb(255,255,255);")
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 0, 1, 2)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_9.setStyleSheet("background-color: rgb(32, 99, 155);\n"
"font: 9pt \"MS Shell Dlg 2\";")
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 0, 1, 2)
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";\n"
"color: rgb(255,255,255);")
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 3, 0, 1, 2)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox_1 = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.groupBox_1.setTitle("")
        self.groupBox_1.setFlat(True)
        self.groupBox_1.setObjectName("groupBox_1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_3.sizePolicy().hasHeightForWidth())
        self.checkBox_3.setSizePolicy(sizePolicy)
        self.checkBox_3.setText("")
        self.checkBox_3.setChecked(False)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_3.addWidget(self.checkBox_3, 1, 2, 1, 1)
        self.doubleSpinBox_1 = QtWidgets.QDoubleSpinBox(self.groupBox_1)
        self.doubleSpinBox_1.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_1.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_1.setSizePolicy(sizePolicy)
        self.doubleSpinBox_1.setStyleSheet("background-color: rgb(35, 35, 35);\n"
"selection-color: rgb(237, 85, 59);\n"
"selection-background-color: rgb(33, 57, 86);\n"
"\n"
"font: 11pt \"Calibri\";")
        self.doubleSpinBox_1.setProperty("showGroupSeparator", False)
        self.doubleSpinBox_1.setDecimals(0)
        self.doubleSpinBox_1.setMinimum(50.0)
        self.doubleSpinBox_1.setMaximum(150.0)
        self.doubleSpinBox_1.setObjectName("doubleSpinBox_1")
        self.gridLayout_3.addWidget(self.doubleSpinBox_1, 1, 3, 1, 1)
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.groupBox_1)
        self.doubleSpinBox_3.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_3.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_3.setSizePolicy(sizePolicy)
        self.doubleSpinBox_3.setStyleSheet("background-color: rgb(35, 35, 35);\n"
"selection-color: rgb(237, 85, 59);\n"
"selection-background-color: rgb(33, 57, 86);\n"
"\n"
"font: 11pt \"Calibri\";")
        self.doubleSpinBox_3.setProperty("showGroupSeparator", False)
        self.doubleSpinBox_3.setDecimals(0)
        self.doubleSpinBox_3.setMinimum(50.0)
        self.doubleSpinBox_3.setMaximum(150.0)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.gridLayout_3.addWidget(self.doubleSpinBox_3, 2, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";\n"
"color: rgb(255,255,255);")
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 4, 0, 1, 2)
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comboBox_4.sizePolicy().hasHeightForWidth())
        self.comboBox_4.setSizePolicy(sizePolicy)
        self.comboBox_4.setStyleSheet("background-color: rgb(35, 35, 35);\n"
"\n"
"selection-color: rgb(237, 85, 59);\n"
"selection-background-color: rgb(33, 57, 86);\n"
"color: rgb(255, 210, 119);\n"
"border-color: rgb(255, 255, 255);\n"
"gridline-color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.comboBox_4.setFrame(False)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_4, 4, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";\n"
"color: rgb(255,255,255);")
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 5, 0, 1, 1)
        self.label_1 = QtWidgets.QLabel(self.groupBox_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_1.sizePolicy().hasHeightForWidth())
        self.label_1.setSizePolicy(sizePolicy)
        self.label_1.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_1.setStyleSheet("background-color: rgb(32, 99, 155);\n"
"font: 9pt \"MS Shell Dlg 2\";")
        self.label_1.setObjectName("label_1")
        self.gridLayout_3.addWidget(self.label_1, 0, 0, 1, 2)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox.setSizePolicy(sizePolicy)
        self.doubleSpinBox.setMinimumSize(QtCore.QSize(0, 26))
        self.doubleSpinBox.setStyleSheet("background-color: rgb(35, 35, 35);\n"
"selection-color: rgb(237, 85, 59);\n"
"selection-background-color: rgb(33, 57, 86);\n"
"font: 12.5pt \"Garamond\";")
        self.doubleSpinBox.setDecimals(0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout_3.addWidget(self.doubleSpinBox, 6, 3, 1, 1)
        self.label_ = QtWidgets.QLabel(self.groupBox_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_.sizePolicy().hasHeightForWidth())
        self.label_.setSizePolicy(sizePolicy)
        self.label_.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_.setStyleSheet("background-color: rgb(32, 99, 155);\n"
"font: 9pt \"MS Shell Dlg 2\";")
        self.label_.setObjectName("label_")
        self.gridLayout_3.addWidget(self.label_, 0, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";\n"
"color: rgb(255,255,255);")
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 2, 0, 1, 1)
        self.comboBox_5 = QtWidgets.QComboBox(self.groupBox_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comboBox_5.sizePolicy().hasHeightForWidth())
        self.comboBox_5.setSizePolicy(sizePolicy)
        self.comboBox_5.setStyleSheet("background-color: rgb(35, 35, 35);\n"
"\n"
"selection-color: rgb(237, 85, 59);\n"
"selection-background-color: rgb(33, 57, 86);\n"
"color: rgb(255, 210, 119);\n"
"border-color: rgb(255, 255, 255);\n"
"gridline-color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.comboBox_5.setFrame(False)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_5, 5, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";\n"
"color: rgb(255,255,255);")
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comboBox_3.sizePolicy().hasHeightForWidth())
        self.comboBox_3.setSizePolicy(sizePolicy)
        self.comboBox_3.setStyleSheet("background-color: rgb(35, 35, 35);\n"
"\n"
"selection-color: rgb(237, 85, 59);\n"
"selection-background-color: rgb(33, 57, 86);\n"
"color: rgb(255, 210, 119);\n"
"border-color: rgb(255, 255, 255);\n"
"gridline-color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.comboBox_3.setFrame(False)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_3, 6, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("background-color: rgb(32, 99, 155);\n"
"font: 9pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 3, 0, 1, 1)
        self.checkBox_1 = QtWidgets.QCheckBox(self.groupBox_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_1.sizePolicy().hasHeightForWidth())
        self.checkBox_1.setSizePolicy(sizePolicy)
        self.checkBox_1.setText("")
        self.checkBox_1.setChecked(False)
        self.checkBox_1.setObjectName("checkBox_1")
        self.gridLayout_3.addWidget(self.checkBox_1, 2, 2, 1, 1)
        self.gridLayout.addWidget(self.groupBox_1, 0, 0, 1, 1)
        self.dockWidget_1.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_1)
        self.dockWidget_4 = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_4.setMinimumSize(QtCore.QSize(250, 487))
        self.dockWidget_4.setObjectName("dockWidget_4")
        self.dockWidgetContents_5 = QtWidgets.QWidget()
        self.dockWidgetContents_5.setObjectName("dockWidgetContents_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.dockWidgetContents_5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.dockWidgetContents_5)
        self.groupBox.setMinimumSize(QtCore.QSize(221, 191))
        self.groupBox.setTitle("")
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_8.addWidget(self.lineEdit, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout_8.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox)
        self.label_21.setObjectName("label_21")
        self.gridLayout_8.addWidget(self.label_21, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_8.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_8.addWidget(self.lineEdit_2, 2, 1, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_8.addWidget(self.lineEdit_3, 3, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.dockWidgetContents_5)
        self.groupBox_5.setMinimumSize(QtCore.QSize(221, 241))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setFlat(True)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_4.addWidget(self.groupBox_5, 1, 0, 1, 1)
        self.dockWidget_4.setWidget(self.dockWidgetContents_5)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_4)
        self.actionRUN = QtWidgets.QAction(MainWindow)
        self.actionRUN.setObjectName("actionRUN")
        self.actionSTOP = QtWidgets.QAction(MainWindow)
        self.actionSTOP.setObjectName("actionSTOP")
        self.menuHelp.addAction(self.actionRUN)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionSTOP)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Physim"))
        self.comboBox_1.setItemText(0, _translate("MainWindow", "Ascending Aorta"))
        self.comboBox_1.setItemText(1, _translate("MainWindow", "Aortic arch"))
        self.radioButton_1.setText(_translate("MainWindow", "Pressure"))
        self.radioButton_2.setText(_translate("MainWindow", "Flow"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Ascending Aorta"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Aortic arch"))
        self.radioButton_3.setText(_translate("MainWindow", "Pressure"))
        self.radioButton_4.setText(_translate("MainWindow", "Flow"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.menuOptions.setTitle(_translate("MainWindow", "Options"))
        self.menuHelp.setTitle(_translate("MainWindow", "Run"))
        self.dockWidget_1.setWindowTitle(_translate("MainWindow", "Input Parameters"))
        self.label_20.setText(_translate("MainWindow", "Value"))
        self.labe.setText(_translate("MainWindow", "Blood viscosity"))
        self.label_7.setText(_translate("MainWindow", "Blood density"))
        self.label_9.setText(_translate("MainWindow", "Property"))
        self.label_13.setText(_translate("MainWindow", "Reflection Coefficient"))
        self.label_5.setText(_translate("MainWindow", "Number of Arteries"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_4.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox_4.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox_4.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox_4.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox_4.setItemText(8, _translate("MainWindow", "9"))
        self.comboBox_4.setItemText(9, _translate("MainWindow", "10"))
        self.comboBox_4.setItemText(10, _translate("MainWindow", "11"))
        self.comboBox_4.setItemText(11, _translate("MainWindow", "12"))
        self.comboBox_4.setItemText(12, _translate("MainWindow", "13"))
        self.comboBox_4.setItemText(13, _translate("MainWindow", "14"))
        self.comboBox_4.setItemText(14, _translate("MainWindow", "15"))
        self.comboBox_4.setItemText(15, _translate("MainWindow", "16"))
        self.comboBox_4.setItemText(16, _translate("MainWindow", "17"))
        self.comboBox_4.setItemText(17, _translate("MainWindow", "18"))
        self.comboBox_4.setItemText(18, _translate("MainWindow", "19"))
        self.comboBox_4.setItemText(19, _translate("MainWindow", "20"))
        self.label_6.setText(_translate("MainWindow", "Select Artery"))
        self.label_1.setText(_translate("MainWindow", "Property"))
        self.label_.setText(_translate("MainWindow", "Value"))
        self.label_4.setText(_translate("MainWindow", "Peak Flow"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_5.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_5.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox_5.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox_5.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox_5.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox_5.setItemText(8, _translate("MainWindow", "9"))
        self.comboBox_5.setItemText(9, _translate("MainWindow", "10"))
        self.comboBox_5.setItemText(10, _translate("MainWindow", "11"))
        self.comboBox_5.setItemText(11, _translate("MainWindow", "12"))
        self.comboBox_5.setItemText(12, _translate("MainWindow", "13"))
        self.comboBox_5.setItemText(13, _translate("MainWindow", "14"))
        self.comboBox_5.setItemText(14, _translate("MainWindow", "15"))
        self.comboBox_5.setItemText(15, _translate("MainWindow", "16"))
        self.comboBox_5.setItemText(16, _translate("MainWindow", "17"))
        self.comboBox_5.setItemText(17, _translate("MainWindow", "18"))
        self.comboBox_5.setItemText(18, _translate("MainWindow", "19"))
        self.comboBox_5.setItemText(19, _translate("MainWindow", "20"))
        self.label_3.setText(_translate("MainWindow", "Heart Rate"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Ascending aorta"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Aortic arch"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "Subclavian artery left"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "Subclavian artery right"))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "Common carotid(L)"))
        self.comboBox_3.setItemText(5, _translate("MainWindow", "Common carotid(R)"))
        self.comboBox_3.setItemText(6, _translate("MainWindow", "Thoracic aorta"))
        self.comboBox_3.setItemText(7, _translate("MainWindow", "Cerebral artery right"))
        self.comboBox_3.setItemText(8, _translate("MainWindow", "Cerebral artery left"))
        self.comboBox_3.setItemText(9, _translate("MainWindow", "Abdominal aorta"))
        self.comboBox_3.setItemText(10, _translate("MainWindow", "Brachial artery right"))
        self.comboBox_3.setItemText(11, _translate("MainWindow", "Brachial artery left"))
        self.comboBox_3.setItemText(12, _translate("MainWindow", "Hepatic artery"))
        self.comboBox_3.setItemText(13, _translate("MainWindow", "Renal artery"))
        self.comboBox_3.setItemText(14, _translate("MainWindow", "Femoral artery left"))
        self.comboBox_3.setItemText(15, _translate("MainWindow", "Femoral artery right"))
        self.comboBox_3.setItemText(16, _translate("MainWindow", "Ulnar artery left"))
        self.comboBox_3.setItemText(17, _translate("MainWindow", "Ulnar artery right"))
        self.comboBox_3.setItemText(18, _translate("MainWindow", "Radial artery left"))
        self.comboBox_3.setItemText(19, _translate("MainWindow", "Radial artery right"))
        self.label.setText(_translate("MainWindow", "Stenosis"))
        self.dockWidget_4.setWindowTitle(_translate("MainWindow", "Waveform"))
        self.label_8.setText(_translate("MainWindow", "SBP"))
        self.label_21.setText(_translate("MainWindow", "DBP"))
        self.label_2.setText(_translate("MainWindow", "Stenosis"))
        self.actionRUN.setText(_translate("MainWindow", "Run.."))
        self.actionSTOP.setText(_translate("MainWindow", "Stop"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
